version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nome_do_banco
      - MYSQL_USER=usuario_do_banco
      - MYSQL_PASSWORD=senha_do_banco
    ports:
      - "3306:3306"

  app:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=projeto.settings
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000

  celery:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=projeto.settings
    command: celery -A projeto worker -l info
    depends_on:
      - db
      - app